# This file generates the GitHub Actions matrix.
# Zephyr 4.1 / HWMv2: nice_nano_v2 -> nice_nano//zmk
---
include:
  - board: nice_nano//zmk
    shield: sofle_left
  - board: nice_nano//zmk
    shield: sofle_right
  - board: nice_nano//zmk
    shield: settings_reset
