# CONFIG_ZMK_IDLE_TIMEOUT=60000
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# CONFIG_ZMK_PM_SOFT_OFF=y

# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

#Disabling PHY 2Mbps
CONFIG_BT_CTLR_PHY_2M=n
#Enabling passkey entry
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# 基础串口配置
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# USB配置
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

# CDC ACM配置
CONFIG_USB_CDC_ACM=y
CONFIG_CDC_ACM_UART_DEVICE_NAME="CDC_ACM_0"

# ZMK USB日志配置
CONFIG_ZMK_USB_LOGGING=y

# 可选：更详细的调试
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3