CONFIG_ZMK_IDLE_TIMEOUT=60000

CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=30

# Use the STRIP config specific to the LEDs you're using

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n