CONFIG_ZMK_IDLE_TIMEOUT=60000
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# 更改键盘默认显示名称
# CONFIG_ZMK_KEYBOARD_NAME="M34"